type Belt {
  belt: String
  batch: Int
}

input BeltInput {
  belt: String
  batch: Int
}

type Cv {
  name: String
  email: String
  photo: String
  belts: [Belt]
  skills: [String]
  biography: String
  phone: String
  interests: [String]
  hobbies: [String]
  website: String
  facebook: String
  twitter: String
  linkedin: String
  github: String

  languages: [String]
}

input CvInput {
  name: String
  email: String
  photo: String
  belts: [BeltInput]
  skills: [String]
  biography: String
  phone: String
  interests: [String]
  hobbies: [String]
  website: String
  facebook: String
  twitter: String
  linkedin: String
  github: String

  languages: [String]
}

type Query {
  hello: String
  cv(uid: String!): Cv
}

type Mutation {
  updateCv(uid: String!, input: CvInput!): Cv
  CreateCv(uid: String!): Cv
}